### ISSUE TITLE
"Seeing double" in rectangular images

### ISSUE THREAD

**Issue by ratinguely** [hoppe93/SOFT2#14]
When using two arguments for pixels (e.g. pixels = 600 300), the resulting image (e.g. png) somehow seems to "overlap" the images. Try changing the pixels in /examples/Image/pi and you'll see this. Perhaps this is a problem with the plotting function and not the actual SOFT simulation?

Also, it seems that pixels = X Y leads to X vertical pixels and Y horizontal pixels, when I would have expected the other way, e.g. pixels = 600 300 makes a tall, skinny image.

Original:
![image](https://github.com/hoppe93/SOFT2/assets/46829818/2b385f89-850b-4ac7-b273-d37271394d45)
With rectangular image:
![image](https://github.com/hoppe93/SOFT2/assets/46829818/f38c9f2f-b292-4244-8786-0e2346a95d02)

**Comment by hoppe93** [comment]
This was a bug in the PNG generation routine in [softlib](https://github.com/hoppe93/softlib) (and also in the corresponding PPM image generator) and should now be fixed. To get the fix, you will need to update softlib (e.g. run ``git pull`` in your softlib directory) and then recompile both softlib and SOFT2 (in that order) by running ``make`` in the ``build`` directory.
